---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akulgoyal/Microservices-demo
          searchPaths: ConfigData
server:
  port: 8001

# For simplicity, disable security when posting to bus/refresh can be resolved by adding actuator in pom:
management:
  security:
    enabled: false